# ---------------------------------------------------
# USER MICROSERVICE
# ---------------------------------------------------
# This is a small FastAPI microservice used
# to simulate internal service communication.
#
# It demonstrates:
# - OpenTelemetry tracing
# - FastAPI instrumentation
# - custom spans
# - observability integration


from fastapi import FastAPI

import asyncio


# OpenTelemetry tracing API
from opentelemetry import trace


# OpenTelemetry resource metadata
from opentelemetry.sdk.resources import (
    Resource
)


# Main tracing provider
from opentelemetry.sdk.trace import (
    TracerProvider
)


# Processes/export spans in batches
from opentelemetry.sdk.trace.export import (
    BatchSpanProcessor
)


# OTLP exporter sends telemetry data
# to observability backend
from opentelemetry.exporter.otlp.proto.http.trace_exporter import (
    OTLPSpanExporter
)


# Automatically instruments FastAPI requests
from opentelemetry.instrumentation.fastapi import (
    FastAPIInstrumentor
)


# ---------------------------------------------------
# FASTAPI APPLICATION
# ---------------------------------------------------

app = FastAPI()


# ---------------------------------------------------
# OPEN TELEMETRY SETUP
# ---------------------------------------------------
# Initializes tracing system for service.
#
# Traces/spans generated by this application
# will be exported to observability backend.


trace.set_tracer_provider(

    TracerProvider(

        resource=Resource.create({

            # service name shown inside
            # observability dashboard
            "service.name": "user-service"

        })
    )
)


# tracer object used for creating spans
tracer = trace.get_tracer(__name__)


# ---------------------------------------------------
# OTLP EXPORTER
# ---------------------------------------------------
# Sends traces to observability backend.
#
# In this example:
# traces are exported to local Jaeger instance.


otlp_exporter = OTLPSpanExporter(

    endpoint="http://localhost:4318/v1/traces"

)


# ---------------------------------------------------
# SPAN PROCESSOR
# ---------------------------------------------------
# Collects spans and exports them in batches.
#
# Batch exporting improves performance compared
# to exporting every span individually.


span_processor = BatchSpanProcessor(

    otlp_exporter

)


# attach span processor to tracing provider
trace.get_tracer_provider().add_span_processor(

    span_processor

)


# automatically traces FastAPI requests
FastAPIInstrumentor.instrument_app(app)


# ---------------------------------------------------
# ENDPOINT
# ---------------------------------------------------
# Simulates internal user service endpoint.
#
# Custom span:
# "fetch-users-from-db"
#
# Artificial delay added to simulate
# database/network latency.


@app.get("/internal-users")
async def internal_users():

    with tracer.start_as_current_span(
        "fetch-users-from-db"
    ):

        # simulate processing delay
        await asyncio.sleep(0.5)

    return {

        "users": [

            "Arron",

            "John",

            "Alice"
        ]
    }